SELECT DISTINCT CP.CART_ID
  FROM CART_PRODUCTS AS CP
 INNER JOIN (SELECT CART_ID, NAME FROM CART_PRODUCTS WHERE Name = 'Yogurt') AS SUBQUERY
    ON CP.CART_ID = SUBQUERY.CART_ID
 WHERE CP.Name = 'Milk';



# WITH A AS
# (
# SELECT CART_ID 
#   FROM CART_PRODUCTS
#  WHERE NAME = 'Milk'
# )
# SELECT DISTINCT CART_PRODUCTS.CART_ID
#   FROM CART_PRODUCTS
#  INNER JOIN A
#     ON A.CART_ID = CART_PRODUCTS.CART_ID
#  WHERE CART_PRODUCTS.NAME = 'Yogurt'; 



# WITH A AS
# (
# SELECT CART_ID, 
#        NAME
#   FROM CART_PRODUCTS
#  WHERE NAME = 'Milk'
# )
# , B AS
# (
# SELECT CART_ID, 
#        NAME
#   FROM CART_PRODUCTS
#  WHERE NAME = 'Yogurt'
# )
# SELECT DISTINCT A.CART_ID
#   FROM A
#  INNER JOIN B
#     ON A.CART_ID = B.CART_ID; 
