-- FOOD_ORDER: PRODUCT_ID, AMOUNT, PRODUCE_DATE
-- FOOD_PRODUCT: PRODUCT_ID, PRODUCT_NAME, PRICE
WITH A AS 
(
    SELECT FO.PRODUCT_ID, 
           AMOUNT, 
           PRODUCE_DATE,
           FP.PRODUCT_NAME,
           FP.PRICE
      FROM FOOD_ORDER AS FO
      LEFT JOIN FOOD_PRODUCT AS FP
        ON FO.PRODUCT_ID = FP.PRODUCT_ID
     WHERE DATE(PRODUCE_DATE) >= '2022-05-01' AND
           DATE(PRODUCE_DATE) < '2022-06-01'
)
SELECT PRODUCT_ID,
       PRODUCT_NAME, 
       SUM(AMOUNT * PRICE) AS TOTAL_SALES
  FROM A
 WHERE PRODUCT_NAME IS NOT NULL
 GROUP BY PRODUCT_ID, PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
     