/* 문제
- 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량을 출력
- OFFLINE_SALE의 USER_ID 는 NULL로
- ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC */

# WITH ONLINE AS
# (
#     SELECT SALES_DATE, 
#            PRODUCT_ID, 
#            USER_ID,
#            SALES_AMOUNT
#       FROM ONLINE_SALE
#      WHERE 1 =1 AND
#            SALES_DATE >= '2022-03-01' AND
#            SALES_DATE <  '2022-04-01'
# )
# SELECT SALES_DATE, 
#        PRODUCT_ID, 
#        IF(USER_ID, NULL),  -- 열이 하나 부족할 경우 어떻게 하지?
#        SALES_AMOUNT
#   FROM OFFLINE_SALE
#  WHERE SALES_DATE >= '2022-03-01' AND
#        SALES_DATE <  '2022-04-01'
#   UNION ALL
#  SELECT *
#    FROM ONLINE
#   ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
  
  
  
  SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION
    SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
    FROM OFFLINE_SALE
) A
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
  





 -- 기존에 없던 열을 추가하고, 그 열을 NULL로 하는 방법은??