-- Solution 1 

WITH A AS
(
SELECT REST_ID, 
       ROUND(AVG(REVIEW_SCORE),2) AS SCORE
  FROM REST_REVIEW
 GROUP BY REST_ID
)
SELECT RI.REST_ID, 
       RI.REST_NAME, 
       RI.FOOD_TYPE, 
       RI.FAVORITES, 
       RI.ADDRESS, 
       SCORE
  FROM A
  RIGHT JOIN REST_INFO AS RI
     ON RI.REST_ID = A.REST_ID
  WHERE RI.ADDRESS LIKE "%서울%" AND
        SCORE IS NOT NULL
  ORDER BY SCORE DESC, RI.FAVORITES DESC;

-- Solution 2

SELECT I.REST_ID,
I.REST_NAME,
I.FOOD_TYPE,
I.FAVORITES,
I.ADDRESS,
ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;
