/* 문제:
- 2022년 1월 도서 판매 데이터
- 저자별 카테고리별 매출액
- AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
- ORDER BY AUTHOR_ID ASC, CATEGORY DESC
*/
WITH A AS 
(
SELECT AUTHOR_ID, 
       CATEGORY, 
       SUM(SALES * PRICE) AS TOTAL_SALES
  FROM BOOK_SALES AS BS
 INNER JOIN BOOK AS B
    ON BS.BOOK_ID = B.BOOK_ID
 WHERE 1=1 
       AND SALES_DATE >= '2022-01-01' 
       AND SALES_DATE < '2022-02-01'
 GROUP BY AUTHOR_ID, CATEGORY
)
SELECT A.AUTHOR_ID,
       AUTHOR.AUTHOR_NAME,
       CATEGORY,
       TOTAL_SALES
  FROM A 
 INNER JOIN AUTHOR
    ON AUTHOR.AUTHOR_ID = A.AUTHOR_ID
 ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
    
    
    
    
    
    
    
    